version: '3.8'
services:
  postgres:
    container_name: mypostgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: service
    ports:
      - "5433:5432"